### PR TITLE
Rewrite gateway message queue to avoid #30

### PR DESCRIPTION
**Pull request by ettersi**
Fixes https://github.com/org-arl/Fjage.jl/issues/30.

### CODE REVIEW

**Comment by notthetup** [comment]
Should we add some tests to test this deadlock?

**Comment by ettersi** [comment]
I was thinking about that but decided against it. There's quite some setup required to recreate the deadlock, and the issue is very specific to the old implementation, so all in all the effort to maintain the test seemed not worth the benefit. What we probably should do at some point, though, is to complement the current unit tests with some longer-running stress tests.

**Comment by ettersi** [comment]
I'm assuming you're mainly worried about congestion? The main difference between the two implementations is that the new version blocks other tasks for slightly longer. Apart from that, the two versions are actually more similar than it may seem. In particular, upon a successful filtering receive, they both copy a potentially significant junk of the remaining messages. This can't be avoided without introducing other tradeoffs, however. 

A circular buffer might help avoiding a few allocations, but I doubt that will make much of a difference. In particular, a circular buffer doesn't help with the copying in the case of a filtering receive, which I expect to be the main bottleneck. Also, it's worth noting that even [channels use a vector as the backing data structure](https://github.com/JuliaLang/julia/blob/5b49c0376522fe42f9682731eeb6a52663c859a0/base/channels.jl#L39)

**Comment by ettersi** [comment]
Just realised that my implementation allows filtering receives to miss some messages. Need to go back to the drawing board...

**Comment by ettersi** [comment]
The issue is that when you're waiting for a particular message, it is somewhat hard to keep track of which messages you have already checked because other receivers may remove messages from the queue while you're pointing at a particular position. I can think of three possible solutions to this issue:

1) Recheck all messages every time a new message comes in. I've updated this PR to implement this strategy. 
2) Have some sophisticated strategy for keeping track of receiver positions. Seemed quite tricky to make this both correct and performant, so didn't pursue. 
3) Split the work of matching messages to receives between sender and receiver: each receiver first checks the queue for a matching message, then if that fails, it registers itself with the sender and from then on the sender checks for each incoming message whether there's a matching receive. I've implemented this strategy in a new PR https://github.com/org-arl/Fjage.jl/pull/35.

**Comment by notthetup** [comment]
I believe the [the JS Gateway](https://github.com/org-arl/fjage/tree/master/gateways/js) implements Option 3) also.

**Comment by ettersi** [comment]
We decided to go with option 3), so closing this in favour of https://github.com/org-arl/Fjage.jl/pull/35.

**Pull request closed without merging**
